[package]
name = "lam"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.10"
thiserror = "1.0"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "machine_bench"
harness = false

[[bin]]
name = "prolog"
path = "src/languages/prolog.rs"