name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Rust
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      # Build your project
      - name: Build
        run: cargo build --verbose

      # Run tests
      - name: Run Tests
        run: cargo test --verbose

      # Run tarpaulin to generate a coverage report (using XML output)
      - name: Run Tarpaulin for Coverage
        run: |
          cargo install cargo-tarpaulin || true
          cargo tarpaulin --out Xml --timeout 120

      # Upload the coverage report to Codecov (this step uses tarpaulin’s output)
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./tarpaulin-report.xml
