name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repo with write permission (needed for committing updates)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # Install the Rust toolchain
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Build your project
      - name: Build
        run: cargo build --verbose

      # Run your tests
      - name: Run tests
        run: cargo test --verbose

      # Install cargo-tarpaulin (if not already cached)
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      # Run Tarpaulin to generate an LCOV coverage report (saved as lcov.info)
      - name: Run coverage analysis with Tarpaulin
        run: cargo tarpaulin --out Lcov --verbose

      # Generate an SVG coverage badge from the LCOV report using a community action
      - name: Generate Coverage Badge
        uses: shogo82148/coverage-to-badge-action@v1
        with:
          lcov-path: lcov.info       # The LCOV file generated by Tarpaulin
          output-path: coverage.svg   # The badge output file

      # (Optional) Upload the coverage badge as an artifact so you can download or inspect it
      - name: Upload Coverage Badge Artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-badge
          path: coverage.svg

      # (Optional) Commit the updated coverage badge back to the repository.
      # This step runs only on push events (not on pull requests).
      - name: Commit coverage badge
        if: github.event_name == 'push'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add coverage.svg
          git commit -m "Update coverage badge" || echo "No changes to commit"
          git push
