name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository with credentials so we can later push badge updates.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2. Install the Rust toolchain.
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # 3. Build the project.
      - name: Build
        run: cargo build --verbose

      # 4. Run tests.
      - name: Run tests
        run: cargo test --verbose

      # 5. Install cargo-tarpaulin.
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      # 6. Run Tarpaulin to generate an LCOV coverage report.
      - name: Run coverage analysis with Tarpaulin
        run: cargo tarpaulin --out Lcov --verbose

      # 7. Setup Node.js so we can run our badge-generation script.
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 8. Install dependencies for badge generation.
      - name: Install badge generation dependencies
        run: npm install lcov-parse badge-maker

      # 9. Generate the Coverage Badge by running the script in your repository.
      - name: Generate Coverage Badge
        run: node scripts/generate-badge.js

      # 10. Upload the generated badge as an artifact using actions/upload-artifact v4.
      - name: Upload Coverage Badge Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: coverage.svg

      # 11. (Optional) Commit the updated badge back to the repository on push events.
      - name: Commit coverage badge
        if: github.event_name == 'push'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add coverage.svg
          git commit -m "Update coverage badge" || echo "No changes to commit"
          git push
